plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

group = 'com.innowise'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {

    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    implementation 'org.projectlombok:lombok:1.18.30'
    implementation 'com.google.code.gson:gson:2.8.9'
    compileOnly 'org.projectlombok:lombok'


    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

jar {
    manifest {
        attributes (
            'Main-Class': 'com.innowise.Main'
        )
    }
}

shadowJar {
    manifest {
        attributes 'Main-Class': 'com.innowise.Main'
    }
}

test {
    useJUnitPlatform()
}